config/routes.rb
  Rails.application.routes.draw do
    
  resources :posts
  root 'home#main'
  get '/main' => 'home#main'
  get '/index' => 'home#index'  
  get '/plus' => 'home#plus'
  get '/plus2' => 'home#plus2'
    get '/timer' => 'home#timer'

  
  get 'home/index'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: 'home#show'
  get 'signout', to: 'sessions#destroy', as: "signout"

  resources :sessions, only: [:create, :destroy]
  resources :home, only: [:show]
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
# app/controllers/applicaiton_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: '게시물이 성공적으로 작성되었습니다.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = from_omniauth(request.env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private
    def from_omniauth(auth)
      user = User.where(provider: auth.provider, uid: auth.uid).first_or_initialize
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save
      return user
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/main.html.erb
<!DOCTYPE html>
<html>
    <head>
        <link href="style2.css" rel="stylesheet" type="text/css"/>
        <title>강남콩</title>
    </head>
    <body>
        <center>
            <br><br><br><br><br><br>
            <img src="assets/logo2.png" width="auto" height="100" alt="Boxus" /><br><br>
            <font size="2"><p>로그인을 하시면 빠르고 다양한 서비스 이용이 가능합니다.<br>
            본 강남콩 서비스는 구글 로그인 서비스를 지원합니다.</p></font><br>
            <!-- 구글 로그인 폼 -->
            <div>
              <% if current_user %>
                강남대학교 <strong><%= current_user.name %></strong> 학우님 반갑습니다!
                <%= link_to "로그아웃", signout_path, id: "sign_out" %> <br><br><br>
            <a href="http://kangmamkong.herokuapp.com/"><img src="assets/gogomok.png" width="auto" height="40" alt="Boxus" /></a><br><br>
            <a href="/index"><img src="assets/z3.png" width="auto" height="40" alt="Boxus" /></a><br><br>
            <a href="#" onclick="javascript:btn()"><img src="assets/66.png" width="auto" height="40" alt="Boxus" /></a><br><br>
              <% else %>
              <div class="login-box">
                <a href="/auth/google_oauth2" id= "sign_in"> <button class="loginBtn loginBtn--google">
                  구글 계정으로 로그인
                </button> </a>
              </div>
              <a href="/index"><font size="2">소셜 로그인 없이 둘러보기</font></a>
              <% end %>
            </div>
            <div>
            </div>
            <br><br>
            <img src="assets/3175.png" width="auto" height="180" alt="Boxus" /><br><br>
            <!-- 구글 로그인 폼 -->
        </center>
        
        <script>
function btn(){
    alert('업데이트 예정입니다');
}
</script>


    </body>
</html>

app/views/home/map.html.erb
        <div id="services" class="section">
            <div class="block content-1170 center-relative">
                <div class="section-title-holder right">
                    <div class="section-num">
                      <h2 class="entry-title">collaboration</h2> 
                    </div>
                </div>
                <div class="section-content-holder left">
                    <div class="content-wrapper">
                        <img src="assets/knu_logo.jpg" alt="">
                        <h1 style="text-align:center">X</h1>
                        <img src="assets/likelion_logo.jpg" alt="">
                        <h2 style="text-align:center">6th Operator<br>Kim hyeon woo & Jeong da hye</h2>
                    </div>
                </div>
                <div class="clear"></div>
            </div>
        </div>

        <!-- Contact -->
        <div id="contact" class="section">
            <div class="block content-1170 center-relative">
                <div class="section-title-holder left">
                    <div class="section-num">
                        <span>
                            15-17
                        </span>
                    </div>
                </div>
                <div class="section-content-holder right">
                    <div class="content-wrapper">
                        <div class="one_half ">
                           <img src="assets/5.jpeg" alt="">
                        </div>
                        <div class="one_half last">
                            <div class="contact-form">
                                <p><input id="name" type="text" name="your-name" placeholder="Name"></p>
                                <p><input id="contact-email" type="email" name="your-email" placeholder="Email"></p>
                                <p><input id="subject" type="text" name="your-subject" placeholder="Subject"></p>
                                <p><textarea id="message" name="your-message" placeholder="Message"></textarea></p>
                                <p><input type="submit" onClick="SendMail()" value="SEND"></p>
                            </div>
                        </div>
                        <div class="clear"></div>
                    </div>
                    <div class="full-width">
                        <iframe src="https://www.google.com/maps/embed?pb=!1m10!1m8!1m3!1d3174.8326971158044!2d127.1290621!3d37.2753942!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sko!2skr!4v1525877785168" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
                    </div>
                </div>
                <div class="clear"></div>
            </div>
        </div>

        <!-- Footer -->

app/views/home/plus.html.erb
<!DOCTYPE HTML>
<html lang="en-US">
    <head>
        <title>Boxus - Html Responsive One Page Template</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta name="description" content="Template by Colorlib" />
        <meta name="keywords" content="HTML, CSS, JavaScript, PHP" />
        <meta name="author" content="Colorlib" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

        <link rel="shortcut icon" href="images/favicon.png" />
        <link href='http://fonts.googleapis.com/css?family=Roboto:300,400,400i,700,700i,900|Montserrat:400,700|PT+Serif' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" type="text/css"  href='css/clear.css' />
        <link rel="stylesheet" type="text/css"  href='css/common.css' />
        <link rel="stylesheet" type="text/css"  href='css/font-awesome.min.css' />
        <link rel="stylesheet" type="text/css"  href='css/carouFredSel.css' />
        <link rel="stylesheet" type="text/css"  href='css/prettyPhoto.css' />
        <link rel="stylesheet" type="text/css"  href='css/sm-clean.css' />
        <link rel="stylesheet" type="text/css"  href='style.css' />

        <!--[if lt IE 9]>
                <script src="js/html5.js"></script>
        <![endif]-->

    </head>
    <body class="single-portfolio">

        <!-- Preloader Gif -->


        <!-- Menu -->
        <div class="menu-wrapper center-relative">
            <nav id="header-main-menu">
                <div class="mob-menu">MENU</div>
                <ul class="main-menu sm sm-clean">
                    <li><a href="#home">Home</a></li>
                    <li><a href="#services">Services</a></li>
                    <li><a href="#portfolio">Portfolio</a></li>
                    <li><a href="#about">About</a></li>
                    <li><a href="#news">News</a></li>
                    <li><a href="#video">Video</a></li>
                    <li><a href="#skills">Skills</a></li>
                    <li><a href="#contact">Contact</a></li>
                </ul>
            </nav>
        </div>



        <article id="portfolio-2" class="section portfolio">
            <div class="center-relative content-1170">
                <div class="entry-content">
                    <div class="content-wrap relative">
                        <a class="absolute x-close" href="index.html#portfolio">
                            <img src="images/icon_x.svg" alt="Close">
                        </a>

                        <script>
                            var aboutImage_speed = "500";
                            var aboutImage_auto = "false";
                            var aboutImage_hover = "true";
                        </script>
                        <div class="image-slider-wrapper relative img aboutImage">
                            <a id="aboutImage_next" class="image_slider_next" href="#"></a>
                            <div class="caroufredsel_wrapper">
                                <ul id="aboutImage" class="image-slider slides">
                                    <li><img src="demo-images/about_img_04.jpg" alt=""></li>
                                    <li><img src="demo-images/about_img_05.jpg" alt=""></li>
                                    <li><img src="demo-images/about_img_06.jpg" alt=""></li>
                                </ul>
                            </div>
                            <div class="clear"></div>
                        </div>

                        <div class="clear"></div>
                        <br>
                        <br>
                        <br>
                        <div class="one_half text-right">
                            <p>
                                <span style="color: #adadad;">Project Name:</span> Handmade<br>
                                <span style="color: #adadad;">Client:</span> Est Lorem<br>
                                <span style="color: #adadad;">Year:</span> 2017
                            </p>
                            <br>
                            <br>
                            <div class="text-right">
                                <a href="#" target="_self" class="button ">Download</a>
                            </div>
                        </div>
                        <div class="one_half last ">
                            <h1>Handmade for Everyone</h1>
                            <p>We choose to go to the moon in this decade and do the other things, not because they are easy.</p>
                            <br>
                            <p>
                                Because they are hard, because that goal will serve to organize and measure the best of our energies and skills, because that challenge is one that we are willing to accept, one we are unwilling to postpone and one.<br>
                            </p>
                        </div>
                        <div class="clear"></div>
                    </div>
                </div>
                <div class="clear"></div>
            </div>



            <!-- Footer -->
            <footer>
                <div class="footer content-1170 center-relative">
                    <ul>
                        <li class="copyright-footer">
                            © 2018 All rights reserved. | Boxus Template by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                        </li>
                        <li class="social-footer">
                            <a href="#"><span class="fa fa-twitter"></span></a>
                            <a href="#"><span class="fa fa-behance"></span></a>
                            <a href="#"><span class="fa fa-dribbble"></span></a>
                            <a href="#"><span class="fa fa-facebook"></span></a>
                            <a href="#"><span class="fa fa-rss"></span></a>
                        </li>
                    </ul>
                </div>
            </footer>
        </article>




        <!--Load JavaScript-->
        <script type="text/javascript" src="js/jquery.js"></script>
        <script type='text/javascript' src='js/jquery.sticky-kit.min.js'></script>
        <script type='text/javascript' src='js/jquery.smartmenus.min.js'></script>
        <script type='text/javascript' src='js/jquery.sticky.js'></script>
        <script type='text/javascript' src='js/jquery.dryMenu.js'></script>
        <script type='text/javascript' src='js/isotope.pkgd.js'></script>
        <script type='text/javascript' src='js/jquery.carouFredSel-6.2.0-packed.js'></script>
        <script type='text/javascript' src='js/jquery.mousewheel.min.js'></script>
        <script type='text/javascript' src='js/jquery.touchSwipe.min.js'></script>
        <script type='text/javascript' src='js/jquery.easing.1.3.js'></script>
        <script type='text/javascript' src='js/imagesloaded.pkgd.js'></script>
        <script type='text/javascript' src='js/jquery.prettyPhoto.js'></script>
        <script type='text/javascript' src='js/main.js'></script>
    </body>
</html>

app/views/home/plus2.html.erb
<!DOCTYPE HTML>
<html lang="en-US">
    <head>
        <title>Boxus - Html Responsive One Page Template</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta name="description" content="Template by Colorlib" />
        <meta name="keywords" content="HTML, CSS, JavaScript, PHP" />
        <meta name="author" content="Colorlib" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

        <link rel="shortcut icon" href="images/favicon.png" />
        <link href='http://fonts.googleapis.com/css?family=Roboto:300,400,400i,700,700i,900|Montserrat:400,700|PT+Serif' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" type="text/css"  href='css/clear.css' />
        <link rel="stylesheet" type="text/css"  href='css/common.css' />
        <link rel="stylesheet" type="text/css"  href='css/font-awesome.min.css' />
        <link rel="stylesheet" type="text/css"  href='css/carouFredSel.css' />
        <link rel="stylesheet" type="text/css"  href='css/prettyPhoto.css' />
        <link rel="stylesheet" type="text/css"  href='css/sm-clean.css' />
        <link rel="stylesheet" type="text/css"  href='style.css' />

        <!--[if lt IE 9]>
                <script src="js/html5.js"></script>
        <![endif]-->

    </head>
    <body class="single-portfolio">

        <!-- Preloader Gif -->


        <!-- Menu -->
        <div class="menu-wrapper center-relative">
            <nav id="header-main-menu">
                <div class="mob-menu">MENU</div>
                <ul class="main-menu sm sm-clean">
                    <li><a href="#home">Home</a></li>
                    <li><a href="#services">Services</a></li>
                    <li><a href="#portfolio">Portfolio</a></li>
                    <li><a href="#about">About</a></li>
                    <li><a href="#news">News</a></li>
                    <li><a href="#video">Video</a></li>
                    <li><a href="#skills">Skills</a></li>
                    <li><a href="#contact">Contact</a></li>
                </ul>
            </nav>
        </div>



        <article id="portfolio-1" class="section portfolio">
            <div class="center-relative content-1170">
                <div class="entry-content">
                    <div class="content-wrap relative">

                        <div class="one margin-0">
                            <img src="assets/horro.jpg" width=50 height=50 alt="">
                        </div>
                        <div class="one margin-0">
                            <img src="assets/horro2.jpg" width=50 height=50 alt="">
                        </div>
                        <div class="one margin-0">
                            <img src="assets/horro3.jpg" width=50 height=50 alt="">
                        </div>
                        
                        <div class="one margin-0">
                            <img src="assets/horro4.jpg" width=50 height=50 alt="">
                        </div>
                        <div class="clear"></div>
                        <br>
                        <br>
                        <br>

                        <div class="one_half text-right">
                            <p>
                                <span style="color: #adadad;">Project Name:</span> Handmade<br>
                                <span style="color: #adadad;">Client:</span> Est Lorem<br>
                                <span style="color: #adadad;">Year:</span> 2017
                            </p>
                           <br>
                           <br>
                            <div class="text-right">
                                <a href="#" target="_self" class="button ">Download</a>
                            </div>
                        </div>
                        <div class="one_half last ">
                            <h1>Handmade for Everyone</h1>
                            <p>We choose to go to the moon in this decade and do the other things, not because they are easy.</p>
                            <br>
                            <p>
                                Because they are hard, because that goal will serve to organize and measure the best of our energies and skills, because that challenge is one that we are willing to accept, one we are unwilling to postpone and one.<br>
                            </p>
                        </div>
                        <div class="clear"></div>
                    </div>
                </div>
                <div class="clear"></div>
            </div>



            <!-- Footer -->
            <footer>
                <div class="footer content-1170 center-relative">
                    <ul>
                        <li class="copyright-footer">
                            © 2018 All rights reserved. | Boxus Template by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                        </li>
                        <li class="social-footer">
                            <a href="#"><span class="fa fa-twitter"></span></a>
                            <a href="#"><span class="fa fa-behance"></span></a>
                            <a href="#"><span class="fa fa-dribbble"></span></a>
                            <a href="#"><span class="fa fa-facebook"></span></a>
                            <a href="#"><span class="fa fa-rss"></span></a>
                        </li>
                    </ul>
                </div>
            </footer>
        </article>




        <!--Load JavaScript-->
        <script type="text/javascript" src="js/jquery.js"></script>
        <script type='text/javascript' src='js/jquery.sticky-kit.min.js'></script>
        <script type='text/javascript' src='js/jquery.smartmenus.min.js'></script>
        <script type='text/javascript' src='js/jquery.sticky.js'></script>
        <script type='text/javascript' src='js/jquery.dryMenu.js'></script>
        <script type='text/javascript' src='js/isotope.pkgd.js'></script>
        <script type='text/javascript' src='js/jquery.carouFredSel-6.2.0-packed.js'></script>
        <script type='text/javascript' src='js/jquery.mousewheel.min.js'></script>
        <script type='text/javascript' src='js/jquery.touchSwipe.min.js'></script>
        <script type='text/javascript' src='js/jquery.easing.1.3.js'></script>
        <script type='text/javascript' src='js/imagesloaded.pkgd.js'></script>
        <script type='text/javascript' src='js/jquery.prettyPhoto.js'></script>
        <script type='text/javascript' src='js/main.js'></script>
    </body>
</html>

app/views/home/timer.html.erb
 <!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>countdown</title>
</head>
<body>
	<div id="my-countdown">
		<!-- display the countdown timer here -->
	</div>
	
	<!-- include jQuery -->
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

	<!-- include underscore.js for template -->
	<script src="//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.4.4/underscore-min.js"></script>
	
	<!-- include the countdown plugin -->
	<script src="assets/jquery.countdown.js"></script>

	<!-- create the template to use for this example -->
	<script type="text/template" id="countdown-tpl">
		<table>
			<tr>
				<th>years</th>
				<th>days</th>
				<th>hours</th>
				<th>minutes</th>
				<th>seconds</th>
			</tr>
			<tr>
				<td><%= y %></td>
				<td><%= d %></td>
				<td><%= h %></td>
				<td><%= m %></td>
				<td><%= s %></td>
			</tr>
		</table>
	</script>

</body>
</html>

// define what options to use


    </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<!DOCTYPE HTML>
<html lang="en-US">
    <head>
        <title>강남콩 : 축제</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta name="description" content="Template by Colorlib" />
        <meta name="keywords" content="HTML, CSS, JavaScript, PHP" />
        <meta name="author" content="Colorlib" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        
        <meta http-equiv="refresh" content="500">

        <!--[if lt IE 9]>
                <script src="js/html5.js"></script>
        <![endif]-->

    </head>
    <body>

        <!-- Menu -->
        <div class="menu-wrapper center-relative">
            <nav id="header-main-menu">
                <div class="mob-menu">메뉴</div>
                <ul class="main-menu sm sm-clean">
                    <li><a href="#home">홈</a></li>
                    <li><a href="#services">리듬파워</a></li>
                    <li><a href="#portfolio">다이나믹 듀오</a></li>
                    <li><a href="#about">위너</a></li>
                    <li><a href="#news">폴킴</a></li>
                    <li><a href="#contact">이하이</a></li>
                    <li><a href="#skills">축제 더보기</a></li>
                </ul>
            </nav>
        </div>

        <!-- Preloader Gif -->


        <!-- Menu -->



        <!-- Home -->

        <div id="home" class="section intro-page">
            <div class="block content-1170 center-relative center-text"><br>
                <img class="top-logo" src="assets/logo2.png" alt="Boxus" />
                <br><br><br><br><br><br><br><br>
                        <br><br><br>
                        
                        <p id="notice"><%= notice %></p>

<img src="assets/board.png" alt="Boxus" /><br><br><br><br>
<table>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <h3>제목 <%= post.title %> </h3>
        <h3>내용 <%= post.content %></h3>
        </tr>
        
        
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>
<button><a href="/posts/new">ddd</a></button>

<!DOCTYPE html>
<html lang="en">
<head>
	<title>Table V02</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/animate/animate.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/select2/select2.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/perfect-scrollbar/perfect-scrollbar.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="css/util.css">
	<link rel="stylesheet" type="text/css" href="css/main.css">
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
					<div class="table">

						<div class="row header">
							<div class="cell">
								제목
							</div>
							<div class="cell">
								축제에 대한 코멘트-!
							</div>

						</div>

						<div class="row">
							<div class="cell" data-title="Full Name">
								Vincent Williamson
							</div>
							<div class="cell" data-title="Age">
								31
							</div>

						</div>

					</div>
			</div>
		</div>
	</div>


	

<!--===============================================================================================-->	
	<script src="vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/bootstrap/js/popper.js"></script>
	<script src="vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="js/main.js"></script>

</body>
</html>
            </div>
        </div>



        <!-- Service -->



                
            </div>
            

            
            <div id="skills" class="section">

                
                <center>
                    <img src="assets/kangnamkong" alt="Load more"><br><br><br>
                    <a href="/"><img src="assets/main3.png" alt="map파일"></a><br><br><br>
                    <a href="/plus"><img src="assets/map.png" alt="map파일"></a><br><br><br>
                    <a href="/plus2"><img src="assets/festival.png" alt="map파일"></a>

                    
                </center>
                

                
            </div>
 
        <!-- Skills -->



        
        <footer>
            <div class="footer content-1170 center-relative">
                <ul>
                    <li class="copyright-footer">
                       <span style="color:white">© 2018.05.15 ~ 2018.05.17 KNU 목양축전</span>  <a href="https://colorlib.com" target="_blank"></a>
                    </li>
                    <br>
                    <li class="social-footer">
                        <a href="https://www.facebook.com/likelionKangnam/?ref=br_rs"><span class="fa fa-facebook"></span></a>
                    </li>
                </ul>
            </div>
        </footer>
        
        <script type="text/javascript" src="assets/jquery.js"></script>
        <script type='text/javascript' src='assets/jquery.sticky-kit.min.js'></script>
        <script type='text/javascript' src='assets/jquery.smartmenus.min.js'></script>
        <script type='text/javascript' src='assets/jquery.sticky.js'></script>
        <script type='text/javascript' src='assets/jquery.dryMenu.js'></script>
        <script type='text/javascript' src='assets/isotope.pkgd.js'></script>
        <script type='text/javascript' src='assets/jquery.carouFredSel-6.2.0-packed.js'></script>
        <script type='text/javascript' src='assets/jquery.mousewheel.min.js'></script>
        <script type='text/javascript' src='assets/jquery.touchSwipe.min.js'></script>
        <script type='text/javascript' src='assets/jquery.easing.1.3.js'></script>
        <script type='text/javascript' src='assets/jquery.prettyPhoto.js'></script>
        <script type='text/javascript' src='assets/main.js'></script>
        

        <SCRIPT language="JavaScript">
         if (self.name != 'reload') {
                 self.name = 'reload';
                 self.location.reload(true);
             }
             else self.name = ''; 
        </SCRIPT>
    </body>
</html>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>